#!/bin/bash

flags=`llvm-config --cflags --ldflags --libs core`
san="-Wall -Werror -fsanitize=address -g3"
files="main.c"

rm -rf comp out.ll out.s exe.out

clang $files $flags $san -o comp && \
./comp $1 && \
llc out.ll -o out.s && \
clang out.s -o exe.out && \
./exe.out
