#!/bin/bash

flags=`llvm-config --cflags --ldflags --libs core`
san="-Wall -Werror -fsanitize=address -g3"
files="main.c"

mkdir -p build
rm -rf ./build/comp ./build/out.ll ./build/out.s ./build/exe.out
clang $files $flags $san -o ./build/comp && \
./build/comp $1 && \
llc ./build/out.ll -o ./build/out.s && \
clang ./build/out.s $san -lc++ -o ./build/exe.out && \
./build/exe.out
echo "exit code $?"
rm -rf ./build/exe.out ./build/out.s ./build/comp */*.dSYM