#pragma once

#include "../header.h"

void enter_scope(Node *node);
void exit_scope();
Node *enclosing_continue();
Node *enclosing_break();
void analyze_block(Node *node);
void analyze_match(Node *node);
void declare_variable(Token *token);
Token *find_variable(char *name, bool *captured);
void declare_function(Node *fn);
void declare_struct(Node *node);
void declare_structs(Node *node);
Node *find_function(char *name);
void analyze_binop(Node *node);
void analyze_fdec(Node *node);
void resolve_struct_type(Token *token);
void analyze_struct(Node *node);
void analyze_id(Node *node);
void analyze_fcall(Node *node);
void analyze_for(Node *node);
void analyze(Node *node);
void type_check_block(Node *node);
void type_check_match(Node *node);
bool is_data_type(Token *token);
TypeRef to_llvm_type(Type type);
TypeRef elem_type(Token *arr, int depth);
TypeRef array_type(Token *arr, int depth);
TypeRef struct_type_of(Node *def);
TypeRef llvm_type_of(Token *token);
Value default_value(Token *token);
void type_check_fcall(Node *node);
void type_check_fdec(Node *node);
bool struct_contains(Node *def, Node *target, int depth);
Token *find_field(Node *def, char *name);
void type_check_dot(Node *node);
void type_check_struct(Node *node);
void type_check_binop(Node *node);
void type_check_array_lit(Node *node);
void type_check_access(Node *node);
void type_check_array_ctor(Node *node);
void type_check_for(Node *node);
void type_check(Node *node);
void setup_paths(char *path_name);
void init_module(char *name);
void finalize_module(char *ll_path);
void debug_enter_function(Token *token);
void debug_exit_function(Token *token);
void set_debug_location(Token *token);
Value get_or_declare(char *name, TypeRef fn_type);
void guard(Token *op, Value is_bad, char *what);
void guard_nonzero(Token *op, Value divisor);
void guard_nonnull(Token *op, Value ptr);
void guard_bound(Token *op, Value ptr);
void guard_index(Token *op, Value idx, Value slice);
void guard_slice(Token *op, Value start, Value end, Value len);
Block here_block();
Value here_func();
void llvm_at(Block block);
Block llvm_block(Value fn, char *name);
Value llvm_alloca(TypeRef type, char *name);
Value llvm_load(TypeRef type, Value ptr, char *name);
void llvm_store(Value value, Value ptr);
Value llvm_gep(TypeRef type, Value ptr, Value *idx, int n, char *name);
Value llvm_icmp(LLVMIntPredicate pred, Value l, Value r, char *name);
Value llvm_fcmp(LLVMRealPredicate pred, Value l, Value r, char *name);
void llvm_br(Block dest);
void llvm_cond_br(Value cond, Block yes, Block no);
Value llvm_call(TypeRef type, Value fn, Value *args, int n, char *name);
Value llvm_extract(Value agg, unsigned index, char *name);
Value llvm_insert(Value agg, Value elem, unsigned index, char *name);
Value llvm_string(char *text, char *name);
Value const_int(TypeRef type, long long value);
Value const_i32(long long value);
Value const_i64(long long value);
TypeRef pointer_to(TypeRef type);
Value llvm_binop(LLVMOpcode op, Value l, Value r, char *name);
Value llvm_ret(Value value);
Value llvm_not(Value value);
Value llvm_int_cast(Value value, TypeRef type);
void llvm_sanitize(Value fn);
MetadataRef llvm_di_subroutine();
MetadataRef llvm_di_function(char *name, int line, MetadataRef type);
MetadataRef llvm_di_location(int line, MetadataRef scope);
MetadataRef llvm_get_location();
void llvm_set_location(MetadataRef loc);

void emit_signature(Node *fn);
Value address_of(Node *node);
Value access_ptr(Node *node);
void code_gen_slice(Node *node);
void code_gen_dot(Node *node);
void code_gen_access(Node *node);
void code_gen_array_lit(Node *node);
Value make_slice(Token *arr, int depth, Value data, Value len);
Value array_calloc(TypeRef elem, Value count, Value esz);
Value build_array(Token *arr, Value *dims, int depth, bool heap);
void code_gen_array_ctor(Node *node);
void free_array(Token *arr, Value slice, int depth);
void code_gen_typeof(Node *node);
void code_gen_sizeof(Node *node);
void code_gen_clean(Node *node);
void code_gen_literal(Node *node);
void code_gen_fdec(Node *node);
void code_gen_id(Node *node);
void code_gen_fcall(Node *node);
void code_gen_body(Node *node);
void code_gen_loop(Node *node);
void code_gen_for_array(Node *node);
void code_gen_for(Node *node);
void code_gen_while(Node *node);
void code_gen_match(Node *node);
void code_gen_if(Node *node);
void code_gen_assign(Node *node);
void code_gen_binop(Node *node);
void code_gen_compound(Node *node);
void code_gen_output(Node *node);
void code_gen(Node *node);
