// HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libgen.h> // dirname
#include <stdbool.h>
#include <ctype.h>
#include <assert.h>
#include <sys/stat.h>
// #include <sys/types.h>
#include <dirent.h>
#include <llvm-c/Analysis.h>
#include <llvm-c/BitWriter.h>
#include <llvm-c/Core.h>
#include <llvm-c/DebugInfo.h>
#include <llvm-c/Target.h>
#include <llvm-c/TargetMachine.h>
#include <llvm/Config/llvm-config.h>

#if LLVM_VERSION_MAJOR >= 13
#    if LLVM_VERSION_MAJOR == 13
// LLVM 13's PassBuilder.h declares LLVMCreatePassBuilderOptions() without
// (void), tripping the strict-prototypes error its own headers switch on
#        undef LLVM_C_STRICT_PROTOTYPES_BEGIN
#        undef LLVM_C_STRICT_PROTOTYPES_END
#        define LLVM_C_STRICT_PROTOTYPES_BEGIN
#        define LLVM_C_STRICT_PROTOTYPES_END
#    endif
#    include <llvm-c/Transforms/PassBuilder.h>
#else
#    include <llvm-c/Transforms/PassManagerBuilder.h>
#endif

typedef LLVMTypeRef TypeRef;
typedef LLVMContextRef Context;
typedef LLVMModuleRef Module;
typedef LLVMBuilderRef Builder;
typedef LLVMBasicBlockRef Bloc;
typedef LLVMValueRef Value;
typedef LLVMTargetDataRef TargetData;
typedef LLVMTargetRef Target;
typedef LLVMTargetMachineRef TargetMachine;
typedef LLVMCodeGenOptLevel CodeGenOptLevel;
typedef LLVMRelocMode RelocMode;
typedef LLVMCodeModel CodeModel;
typedef LLVMTypeKind TypeKind;
typedef LLVMAttributeRef AttributeRef;
typedef LLVMMetadataRef MetadataRef;
#if LLVM_VERSION_MAJOR >= 13
typedef LLVMErrorRef Error;
typedef LLVMPassBuilderOptionsRef PassBuilderOptions;
#endif

#define PointerType         LLVMPointerTypeKind
#define IntegerType         LLVMIntegerTypeKind
#define FloatType           LLVMFloatTypeKind
#define DoubleType          LLVMDoubleTypeKind
#define VoidType            LLVMVoidTypeKind
#define FunctionType        LLVMFunctionTypeKind
#define StructType          LLVMStructTypeKind

#define CodeGenLevelDefault LLVMCodeGenLevelDefault
#define RelocDefault        LLVMRelocDefault
#define CodeModelDefault    LLVMCodeModelDefault

// TYPEDEFS
typedef struct Arena Arena;
typedef struct Ura Ura;
typedef struct Token Token;
typedef struct Node Node;
typedef enum Type Type;
typedef struct NodePrint NodePrint;
typedef struct ASM ASM;

// MACROS
#define FILE       __FILE__
#define LINE       __LINE__
#define FUNC       __func__
#define TAB        4

#define RESET      "\033[0m"
#define BOLD       "\033[1m"
#define GREEN(fmt) BOLD "\033[0;32m" fmt RESET
#define RED(fmt)   BOLD "\033[0;31m" fmt RESET
#define CYAN(fmt)  BOLD "\033[0;36m" fmt RESET
#define DIM(fmt)   "\033[2m" fmt RESET

#define expand(type, name) \
    type *name;            \
    size_t name##_count;   \
    size_t name##_size;

#define push_back(parent, child)                                          \
    {                                                                     \
        if (parent##_size == 0)                                           \
            parent = ura_alloc((parent##_size = 10), sizeof(*parent));    \
        else if (parent##_count + 1 == parent##_size) {                   \
            void *tmp = ura_alloc((parent##_size *= 2), sizeof(*parent)); \
            memcpy(tmp, parent, (parent##_count * sizeof(*parent)));      \
            parent = tmp;                                                 \
        }                                                                 \
        parent[parent##_count++] = child;                                 \
    }

// TODO: fix those
#define eprint(...) _eprint(FILE, FUNC, LINE, __VA_ARGS__)
// #define error(...) _error(FILE, FUNC, LINE, __VA_ARGS__)
#define help(...)   printf(__VA_ARGS__)

#ifndef bool
#    define bool  int
#    define true  1
#    define false 0
#endif

#if defined(__APPLE__)
#    include <mach-o/dyld.h>
typedef struct __sFILE *File;
#elif defined(__linux__)
typedef struct _IO_FILE *File;
#endif

// PROTOTYPES (generated by build in config.sh)
#include "proto.h"

// STRUCTS / ENUMS
// clang-format off
struct Arena {
    void *buf;
    size_t size;
    size_t used;
    Arena *next;
};

enum Type {
    // clang-format off
    NONE, ERR, SCOPE,
    
    ID,

    VAR_DEC, VAR, VAR_LOAD,

    VAL_CREATE,

    TEMPLATE_DEC, TEMPLATE_TYPE, TEMPLATE_INIT,
    VOID, BOOL, I8, I32, CHARS,
    REF,
    NULL_,

    STRUCT_DEC, DOT, ATTR,

    OWN, DREF,

    LPARENT, RPARENT, DOTS, COMA,
    LBRACK, RBRACK,
    ARRAY, ARRAY_LIT, ACCESS,

    ASSIGN,
    ADD_ASSIGN, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    ADD, SUB, MUL, DIV, MOD,

    GT, LT, GE, LE, EQ, NQ,

    AND, OR,

    PROTO,
    FN_DEC, ARGS, VARIADIC, FN_CALL, RETURN,
    SIZEOF,

    IF, ELIF, ELSE,
    WHILE, BRK, CNT,

    END,
    // clang-format on
};

struct ASM {
    Value elem;
    Bloc bloc;
    TypeRef type;

    // while loop stuff
    Bloc cond;
    Bloc then;
    Bloc end;
};

struct Token {
    Type type;
    char *name;
    bool is_type;
    int space;

    int line;
    int s;
    int e;

    struct {
        struct {
            char *name;
            char *path;
            char *dir;
            char *buff;
            size_t len;

            char *build_dir;
            char *ll_path;
        } file;
        struct {
            long value;
        } i32;
        struct {
            int value; // TODO: check unicode stuff
        } i8;
        struct {
            int value;
        } b1;
        struct {
            char *value;
        } chars;
    };
};

struct Node {
    Token *token;
    Node *left;
    Node *right;

    expand(Node *, children);
};

struct Ura {
    Arena *arena_head;
    Arena *arena_curr;
    size_t arena_count;
    size_t heap_used;

    char *exec;
    int errors_count;

    // uraFile *curr_file;
    // int curr_line;

    expand(Token *, tokens);

    expand(Node *, scopes);
    Node *scope;

    int exe_pos;

    Context context;
    Module module;
    Builder builder;
};

// Global Ura
Ura ura;

const char *to_string(Type type) {
    char *types[END + 1] = {
        // clang-format off
        [ERR] = "ERR",
        [ID] = "IDENTIFER",
        [SCOPE] = "SCOPE",

        [VAR_DEC] = "VAR_DEC", [VAR] = "VAR", [VAR_LOAD] = "VAR_LOAD",
        [VAL_CREATE] = "VAL_CREATE",
        [TEMPLATE_DEC] = "TEMPLATE_DEC", [TEMPLATE_TYPE] = "TEMPLATE_TYPE",
        [TEMPLATE_INIT] = "TEMPLATE_INIT",

        [VOID] = "VOID", [BOOL] = "BOOL", [I8] = "I8", [I32] = "I32",
        [CHARS] = "CHARS",
        [REF] = "REF",
        [NULL_] = "NULL",

        [STRUCT_DEC] = "STRUCT_DEC", [DOT] = "DOT", [ATTR] = "ATTR",

        [OWN] = "OWN", [DREF] = "DREF",

        [LPARENT] = "LPARENT", [RPARENT] = "RPARENT",
        [LBRACK] = "LBRACK", [RBRACK] = "RBRACK", 
        [DOTS] = "DOTS", [COMA] = "COMA",
        
        [ARRAY] = "ARRAY", [ARRAY_LIT] = "ARRAY_LIT",
        [ACCESS] = "ACCESS",
        
        [ASSIGN] = "ASSIGN",
        [ADD_ASSIGN] = "ADD_ASSIGN", [SUB_ASSIGN] = "SUB_ASSIGN",
        [MUL_ASSIGN] = "MUL_ASSIGN", [DIV_ASSIGN] = "DIV_ASSIGN",
        [MOD_ASSIGN] = "MOD_ASSIGN",

        [ADD] = "ADD", [SUB] = "SUB", [MUL] = "MUL",
        [DIV] = "DIV", [MOD] = "MOD",

        [GT] = "GT", [LT] = "LT", [GE] = "GE",
        [LE] = "LE", [EQ] = "EQ", [NQ] = "NQ",

        [AND] = "AND", [OR] = "OR",

        [PROTO] = "PROTO",
        [FN_DEC] = "FN_DEC", [ARGS] = "ARGS", [VARIADIC] = "VARIADIC",
        [FN_CALL] = "FN_CALL", [RETURN] = "RETURN",
        [SIZEOF] = "SIZEOF",

        [IF] = "IF", [ELIF] = "ELIF", [ELSE] = "ELSE",
        [WHILE] = "WHILE", [BRK] = "BRK", [CNT] = "CNT",

        [END] = "END",
        // clang-format on
    };
    if (types[type] == NULL)
        return "UNKNOWN";
    return types[type];
}

void parse_args(int ac, char **av) {
    if (ac < 2) {
        eprint("expected an argument:\n");
        help("%s <file>.ura\n", av[0]);
        return;
    }
    ura.exec = "exe.out";
    for (int i = 1; i < ac && ura.errors_count == 0; i++) {
        char *arg = av[i];
        if (ura_cmp(arg, "-o")) {
            if (i + 1 >= ac) {
                eprint("expected argument:\n");
                help("-o exe.out\n");
                exit(1);
            }
            ura.exec = av[++i];
        } else {
            size_t n = strlen(arg);
            bool is_ura = n > 4 && ura_cmp(arg + n - 4, ".ura");
            if (!is_ura) {
                eprint("Invalid file '%s'\n", arg);
                help("use %s.ura\n", arg);
                exit(1);
            }
            new_file(arg, -TAB);
        }
    }
}

#include "./assert.c"

Token *new_token(Type type, Token *from) {
    Token *new = ura_alloc(1, sizeof(Token));
    new->type = type;
    if (from) {
        new->space = from->space;
        new->line = from->line;
        new->s = from->s;
        new->e = from->e;
    }
    push_back(ura.tokens, new);
    print("new token %k\n", new);
    return new;
}

char *parse_escaped(char *input, size_t s, size_t e) {
    char *res = ura_alloc(e - s + 1, sizeof(char));
    size_t r = 0;
    while (s < e) {
        int c = -1;
        // clang-format off
        if(s < e && input[s] == '\\')
        {
            switch(input[s + 1]) {
            case 'n':  c = '\n'; break;
            case 't':  c = '\t'; break;
            case 'r':  c = '\r'; break;
            case 'b':  c = '\b'; break;
            case 'f':  c = '\f'; break;
            case 'v':  c = '\v'; break;
            case 'a':  c = '\a'; break;
            case '\\': c = '\\'; break;
            case '"':  c = '\"'; break;
            case '\'': c = '\''; break;
            case '?':  c = '\?'; break;
            case '0':  c = '\0'; break;
            // TODO: add octal stuff etc...
            default: break;
            }
            if(c != -1) s += 2;
            else c = input[s++];
        }
        else c = input[s++];
        // clang-format on
        res[r++] = c;
    }
    return res;
}

Token *parse_token(Type type, int s, int e, int space) {
    Token *new = new_token(type, NULL);
    char *buff = ura.scope->token->file.buff;

    switch (type) {
    case ID: {
        struct {
            char *value;
            Token token;
        } keywords[] = {
            // clang-format off
        { "b1", { .type = BOOL, .is_type = true } },
        { "char", { .type = I8, .is_type = true } },
        { "i8", { .type = I8, .is_type = true } },
        { "i32", { .type = I32, .is_type = true } },
        { "template", { .type = TEMPLATE_DEC, .is_type = true }},

        { "True", { .type = BOOL, .b1 = { .value = true } } },
        { "False", { .type = BOOL, .b1 = { .value = false } } },

        { "struct", { .type = STRUCT_DEC } },
        { "and", { .type = AND } }, { "or", { .type = OR } },
        { "proto", { .type = PROTO } }, { "fn", { .type = FN_DEC } },
        { "return", { .type = RETURN } },
        { "if", { .type = IF } }, { "elif", { .type = ELIF } },
        { "else", { .type = ELSE } },
        { "while", { .type = WHILE } }, { "break", { .type = BRK } },
        { "continue", { .type = CNT } },
        { "null", {.type = NULL_ } },

        { NULL },
            // clang-format on
        };

        size_t i = 0;
        for (; keywords[i].value; i++) {
            char *value = keywords[i].value;
            size_t len = strlen(value);
            if (e - s == len && ura_ncmp(buff + s, value, e - s)) {
                *new = keywords[i].token;
                break;
            }
        }
        if (keywords[i].value)
            break;
        new->name = ura_ndup(buff + s, e - s);
        break;
    }
    case CHARS: {
        new->chars.value = parse_escaped(buff, s + 1, e - 1);
        break;
    }
    case I8: {
        char *str = parse_escaped(buff, s + 1, e - 1);
        if (strlen(str) > 1)
            check_char(s, e, ura.scope->token->line);
        new->i8.value = str[0];
        break;
    }
    case I32: {
        new->i32.value = strtol(buff + s, NULL, 10);
        break;
    }
    default: {
        break;
    }
    }
    new->line = ura.scope->token->line;
    new->s = s;
    new->e = e;
    new->space = space / TAB + (space % TAB != 0);
    return new;
}

void tokenize(Node *node) {
    enter_scope(node);
    Token *token = node->token;
    open_file(token);
    char *buff = token->file.buff;
    assert(buff != NULL);
    arena_reserve(strlen(buff) * 192);

    size_t s = 0;
    size_t e = 0;
    int space = 0;
    while (buff[e]) {
        s = e;
        int line = ura.scope->token->line;
        if (isspace(buff[e])) {
            while (buff[e] == '\n') {
                ura.scope->token->line++;
                e++;
            }
            if (buff[s] == '\n') {
                space = 0;
                s = e - 1;
            }
            while (isspace(buff[e]) && buff[e] != '\n') {
                if (buff[s] == '\n') // beginning of line
                    space++;
                e++;
            }
            continue;
        }

        while (ura_ncmp(buff + s, "//", 2) && buff[e] && buff[e] != '\n')
            e++;
        if (e != s)
            continue;
        if (ura_ncmp(buff + s, "/*", 2)) {
            s += 2; // skip /*
            while (buff[e] && !ura_ncmp(buff + e, "*/", 2))
                e++;

            if (!check_multi_comment(s, e, line))
                break;
            e += 2;
            continue;
        }

        if (buff[s] && strchr("\"\'", buff[s])) {
            char c = buff[s];
            e++;

            while (buff[e] && buff[e] != c && buff[e] != '\n') {
                if (buff[e] == '\\' && buff[e + 1] && buff[e + 1] != '\n')
                    e++;
                e++;
            }
            if (!check_quote(s, e, line))
                break;
            e++; // skip last "
            parse_token(c == '"' ? CHARS : I8, s, e, space);
            continue;
        }

        while (isdigit(buff[e]))
            e++;
        if (e != s) {
            if (!check_number_fits(s, e, line))
                break;
            parse_token(I32, s, e, space);
            continue;
        }

        while (isalpha(buff[s]) && (isalnum(buff[e]) || buff[e] == '_'))
            e++;
        if (e != s) { // found ID
            parse_token(ID, s, e, space);
            continue;
        }

        struct {
            char *value;
            Type type;
        } specials[] = {
            // clang-format off
            {"(", LPARENT}, {")", RPARENT}, {":", DOTS},
            {"[", LBRACK}, {"]", RBRACK},
            {"+=", ADD_ASSIGN}, {"-=", SUB_ASSIGN}, {"*=", MUL_ASSIGN},
            {"/=", DIV_ASSIGN}, {"%=", MOD_ASSIGN},
            {"...", VARIADIC}, {".", DOT},
            {"+", ADD}, {"-", SUB}, {"*", MUL}, {"/", DIV}, {"%", MOD},
            {">=", GE}, {"<=", LE}, {">", GT}, {"<", LT},
            {"==", EQ}, {"!=", NQ},
            {"=", ASSIGN}, {",", COMA},
            {"&&", AND}, {"||", OR},
            {"&", REF},
            {NULL, NONE}
            // clang-format on
        };

        for (int i = 0; specials[i].value; i++) {
            size_t len = strlen(specials[i].value);
            if (ura_ncmp(specials[i].value, buff + e, len)) {
                parse_token(specials[i].type, e, e + len, space);
                if (specials[i].type == DOTS)
                    space += TAB;
                e += len;
            }
        }
        if (e != s)
            continue;

        check_unkown_char(s, e, line);
        break;
    }
    new_token(END, NULL); // TODO: check if it can be removed
    exit_scope();
}

// NODE STUFF

Node *new_node(Token *token) {
    Node *new = ura_alloc(1, sizeof(Node));
    new->token = token;
    print("new node %k\n", token);
    return new;
}

void enter_scope(Node *node) {
    Token *token = node->token;
    print("%s: %t %s\n", CYAN("enter scope"), token->type, token->name);
    ura.scope = node;
    push_back(ura.scopes, node);
}

void exit_scope() {
    Token *token = ura.scope->token;
    print("%s: %t %s\n", CYAN("exit scope"), token->type, token->name);
    ura.scopes_count--;
    ura.scopes[ura.scopes_count] = NULL;
    ura.scope = ura.scopes_count == 0 ? NULL : ura.scopes[ura.scopes_count - 1];
}

bool inside(int space) {
    return ura.tokens[ura.exe_pos]->space > space;
}

Token *peek(int pos) {
    assert(ura.exe_pos + pos <= ura.tokens_count);
    return ura.tokens[ura.exe_pos + pos];
    return NULL;
}

Token *next(void) {
    Token *token = peek(0);
    ura.exe_pos++;
    return token;
}

Node *parse_prime(void) {
    Token *token = next();
    Node *node = NULL;
    switch (token->type) { // clang-format off
    case I32: {
        if(token->name == NULL) {
            node = new_node(new_token(VAL_CREATE, token));
            node->left = new_node(token);
            return node;
        }
        return new_node(token);
    }
    case ID: {
        if(peek(0)->type == LPARENT) { // FN_CALL
            next();
            if(ura_cmp(token->name, "main")) { // main
                node = new_node(token);
                enter_scope(node);
                // assert RPAR
                next();
                // assert :
                next();
                token->type = FN_DEC;
                while(inside(token->space)) {
                    Node *child = parse_prime();
                    // Node *child = parse_expr(0);
                    // push_back(node->children, parse_expr(0));
                    push_back(node->children, child);
                }
                exit_scope();
                return node;
            }

        }
        return new_node(token);
    }
    case FN_DEC: {
        node = new_node(token);
        token = next(); // TODO: assert is ID
        node->token->name = token->name;
        enter_scope(node);

        next(); // skip (
        next(); // skip )
        next(); // skip :
        next(); // skip data_type
        

        exit_scope();
        return node;
    }
    case RETURN: {
        node = new_node(token);
        // TODO: we need to make sure it's on same space
        node->left = parse_expr(0);
        return node;
    }
    case SCOPE: {
        return new_node(token);
    }
    default:
        eprint("handle this case %t\n", token->type);
        exit(1);
    } // clang-format on
    return NULL;
}

Node *parse_expr(int min_op) {
    Node *left = parse_prime();
    if (left->token->type == SCOPE) {
        enter_scope(left);
        while (inside(left->token->space)) {
            Node *child = parse_expr(0);
            assert(child != NULL);
            if (child)
                push_back(left->children, child);
        }
        exit_scope();
        return left;
    }
    while (true) {
        int prec[END + 1] = {
            // clang-format off
            [ASSIGN] = 1,     [ADD_ASSIGN] = 1, [SUB_ASSIGN] = 1,
            [MUL_ASSIGN] = 1, [DIV_ASSIGN] = 1, [MOD_ASSIGN] = 1,

            [OR] = 11,        [AND] = 12,

            [EQ] = 21,        [NQ] = 21,        [GT] = 22,
            [LT] = 22,        [GE] = 22,        [LE] = 22,

            [ADD] = 30,       [SUB] = 30,       [MUL] = 31,
            [DIV] = 31,       [MOD] = 31,

            [DOT] = 41,
            // clang-format on
        };

        int op = prec[peek(0)->type];
        // assert(op != 0);
        if (op <= min_op)
            break;
        Node *node = new_node(next());
        node->left = left;
        node->right = parse_expr(op);
        left = node;
    }
    return left;
}

void analyze(Node *node) {
    switch (node->token->type) {
    case SCOPE: {
        enter_scope(node);
        for (int i = 0; i < node->children_count; i++) {
            Node *child = node->children[i];
            analyze(child);
        }
        exit_scope();
        break;
    }
    case I32: {
        break;
    }
    case FN_DEC: {
        for (int i = 0; i < node->children_count; i++) {
            Node *child = node->children[i];
            analyze(child);
        }
        break;
    }
    case RETURN: {
        analyze(node->left);
        break;
    }
    default:
        break;
    }
}

void codegen_beg(Node *node) {
    ura.context = LLVMContextCreate();
    ura.module = LLVMModuleCreateWithNameInContext(name, ura.context);
    ura.builder = LLVMCreateBuilderInContext(ura.context);

    LLVMInitializeNativeTarget();
    LLVMInitializeNativeAsmPrinter();
    // LLVMInitializeNativeAsmParser(); // TODO: to be checked

    char *triple = LLVMGetDefaultTargetTriple();
    LLVMSetTarget(ura.module, triple);
    Target target;
    if (!LLVMGetTargetFromTriple(triple, &target, NULL)) {
        CodeGenOptLevel level = CodeGenLevelDefault;
        RelocMode reloc = RelocDefault;
        CodeModel model = CodeModelDefault;
        TargetMachine machine;
        machine = LLVMCreateTargetMachine(target, triple, "", "", level, reloc, model);
        TargetData layout = LLVMCreateTargetDataLayout(machine);
        LLVMSetModuleDataLayout(ura.module, layout);
        LLVMDisposeTargetData(layout);
        LLVMDisposeTargetMachine(machine);
    }
    LLVMDisposeMessage(triple);

    // TODO: add asan stuff here
    // TODO: add flags stuff (Passes)
}

void codegen_end(Node *node) {
}

void codegen(Node *node) {
    switch (node->token->type) {
    case FN_DEC: {
        break;
    }
    case SCOPE: {
        enter_scope(node);
        for (int i = 0; i < node->children_count; i++) {
            Node *child = node->children[i];
            codegen(child);
        }
        exit_scope();
        break;
    }
    default:
        break;
    }
}

/*
TODO:
    [*] open file
    [*] tokenize it
    [*] ast:
      [*] function main
      [*] return something

    [ ] remaining:
        [ ] drop method
        [ ] String struct
        [ ] to_string method
        [ ] output (should handl also struct.to_string)
        [ ] for template add a part in the code thaht JIT/interpreter
        [ ] operators overload
        [ ] for loops over a range: for i in 0..10
        [ ] more integer types (i8, i64, unsigned) and casting with as
        [ ] function inside function
        [ ] learn some design patterns
        [ ] support: macos, windows
*/

int main(int ac, char **av) {
    atexit(ura_free);
    parse_args(ac, av);
    for (size_t i = 0; i < ura.scopes_count; i++) {
        Node *scope = ura.scopes[i];
        print(GREEN("======================================\n"));
        print(GREEN("[TOKENIZE]:\n"));
        tokenize(scope);
        for (int i = 0; i < ura.tokens_count; i++)
            print(CYAN("token ") "%k\n", ura.tokens[i]);
        print(GREEN("======================================\n"));
        print(GREEN("[PARSE]:\n"));
        Node *node = parse_expr(0);
        print("%n", node);
        print(GREEN("======================================\n"));
        print(GREEN("[ANALYZE]:\n"));
        analyze(node);
        print("%n", node);
        print(GREEN("======================================\n"));
        print(GREEN("[CODE GEN]:\n"));
        codegen_beg(node);
        codegen(node);
        codegen_end(node);

#if 0
#endif
    }
}

// MEMORY
Arena *new_arena(size_t size) {
    Arena *new = calloc(1, sizeof(Arena));
    if (new == NULL) {
        eprint("calloc failed\n");
        exit(1);
    }
    new->buf = calloc(size, 1);
    if (new->buf == NULL) {
        eprint("calloc failed\n");
        exit(1);
    }
    new->size = size;
    ura.arena_count++;
    ura.heap_used += (size + sizeof(Arena));
    return new;
}

// clang-format off
void arena_reserve(size_t size) {
    Arena *curr = ura.arena_curr;
    if (curr && curr->size - curr->used >= size) return;
    Arena *new = new_arena((size + 16 - 1) / 16 * 16);
    if (curr) curr->next = new;
    else ura.arena_head = curr;
    ura.arena_curr = new;
}

void *ura_alloc(size_t asked_count, size_t asked_size) {
    Arena *curr = ura.arena_curr;

    size_t asked = asked_count * asked_size;
    asked = (asked + 16 - 1)  / 16 * 16;

    Arena *head = ura.arena_head;
    if (head == NULL || curr->used + asked >= curr->size) {
        size_t size = 1 << 8;
        if (curr != NULL) size = curr->size << 1;
        while (size < asked) size <<= 1;
        Arena *arena = new_arena(size);

        if(ura.arena_head == NULL) { // first time
            ura.arena_head = arena;
            curr = ura.arena_head;
        }
        else {
            curr->next = arena;
            curr = curr->next;
        }
    }
    void *res = curr->buf + curr->used;
    curr->used += asked;
    ura.arena_curr = curr;
    return res;
}
// clang-format on

void ura_free() {
    Arena *curr = ura.arena_head;
    while (curr) {
        Arena *next = curr->next;
        free(curr->buf);
        free(curr);
        curr = next;
    }
}

char *ura_dup(char *str) {
    char *res = ura_alloc(strlen(str) + 1, sizeof(char));
    strcpy(res, str);
    return res;
}

char *ura_ndup(char *str, size_t n) {
    char *res = ura_alloc(n + 1, sizeof(char));
    strncpy(res, str, n);
    return res;
}

// clang-format off
bool ura_cmp(char *left, char *right) {
    size_t i = 0;
    while (left[i] && left[i] == right[i]) i++;
    return left[i] == '\0' && right[i] == '\0';
}

bool ura_ncmp(char *left, char *right, size_t n) {
    size_t i = 0;
    while (i < n && left[i] && left[i] == right[i]) i++;
    return i == n;
}
// clang-format on

// FILE MANAGEMENT
Token *new_file(char *name, int space) {
    Token *new = ura_alloc(1, sizeof(Token));
    new->type = SCOPE;

    new->space = space;
    new->name = ura_dup(name);

    char *path = realpath(name, NULL);
    if (path == NULL) {
        eprint("realpath failed\n");
        exit(1);
    }
    new->file.path = ura_dup(path);
    free(path);
    new->file.dir = dirname(ura_dup(new->file.path));
    push_back(ura.scopes, new_node(new));
    return new;
}

void open_file(Token *token) {
    token->file.build_dir = format("%s/build", token->file.dir);
    DIR *dir = opendir(token->file.build_dir);
    if (dir) {
        closedir(dir);
    } else if (mkdir(token->file.build_dir, 0755) != 0) {
        eprint("mkdir failed\n");
        exit(1);
    }

    File fp = fopen(token->file.path, "r");
    if (fp == NULL) {
        eprint("fopen failed\n");
        exit(1);
    }
    if (fseek(fp, sizeof(char), SEEK_END)) {
        eprint("mkdir failed\n");
        exit(1);
    }
    token->file.len = (size_t)ftell(fp);
    rewind(fp);
    token->file.buff = ura_alloc(token->file.len + 1, sizeof(char));
    fread(token->file.buff, token->file.len, sizeof(char), fp);
    fclose(fp);
}

// UTILS
bool includes(Type to_find, ...) {
    va_list ap;
    va_start(ap, to_find);
    Type curr = va_arg(ap, Type);
    while (curr) {
        if (curr == to_find)
            return true;
        curr = va_arg(ap, Type);
    }
    return false;
}

// FORMATING / PRINTING
// clang-format off
int _print_type(File fp, Node *node) {
    if (node == NULL) return fprintf(fp, "void");
    switch(node->token->type) {
    case REF:        return fprintf(fp, "&") + _print_type(fp, node->left);
    case STRUCT_DEC: return fprintf(fp, "%s", node->token->name);
    case BOOL:       return fprintf(fp, "b1");
    case I8:         return fprintf(fp, "i8");
    case I32:        return fprintf(fp, "i32");
    case NULL_:      return fprintf(fp, "null");
    case ARRAY:      return _print_type(fp, node->left) + fprintf(fp, "[]");
    default:         return fprintf(fp, "%s", to_string(node->token->type));
    }
};

int _print_token(File fp, Token *token) {
    if (token == NULL) return fprintf(fp, "(null token)");
    int r = fprintf(fp, "%s", to_string(token->type));
    if (token->name != NULL) r += fprintf(fp, " name (%s)", token->name);
    if(token->name == NULL && !token->is_type) {
        switch(token->type) {
        case I8:    r += fprintf(fp, " value (%c)", token->i8.value); break;
        case I32:   r += fprintf(fp, " value (%ld)", token->i32.value); break;
        case CHARS: r += fprintf(fp, " value (%s)", token->chars.value); break;
        case BOOL: {
            char *b1 = token->b1.value ? "True" : "False";
            r += fprintf(fp, " value (%s)", b1);
            break;
        }
        default: break;
        }
    }
    r += fprintf(fp, " space (%d)", token->space);
    return 0;
}

struct NodePrint {
    expand(int, depths);
    expand(Node*, nodes);
};

void _print_node_helper(NodePrint *elems, Node *node, int depth) {
    if(node == NULL) return;

    push_back(elems->nodes, node);
    push_back(elems->depths, depth);

    if (!includes(node->token->type, BRK, CNT, 0)) {
        Node *left = node->left;
        bool is_struct = left && left->token->type == STRUCT_DEC;
        if (includes(node->token->type, ID, VAR, REF, 0) && is_struct) {
            push_back(elems->nodes, left);
            push_back(elems->depths, depth + 3);
        } 
        else _print_node_helper(elems, left, depth + 3);
    }
    if (!includes(node->token->type, FN_CALL, 0))
        _print_node_helper(elems, node->right, depth + 3);
    for (size_t i = 0; i < node->children_count; i++)
        _print_node_helper(elems, node->children[i], depth + 3);
}

bool is_open(NodePrint *elems, size_t i, int level) {
    for (size_t j = i + 1; j < elems->nodes_count; j++) {
        if (elems->depths[j] <= level)
            return elems->depths[j] == level;
    }
    return 0;
}

int _print_node(File fp, Node *node) {
    NodePrint elems = {};
    int r = 0;
    _print_node_helper(&elems, node, 0);

    for (size_t i = 0; i < elems.nodes_count; i++) {
        int depth = elems.depths[i];
        for (int level = 1; level < depth; level++)
            r += fprintf(fp, "%s", is_open(&elems, i, level) ? "│ " : " ");
        if (depth) r += fprintf(fp, "%s", is_open(&elems, i, depth) ? "├─" : "└─");
        r += _print_token(fp, elems.nodes[i]->token) + fprintf(fp, "\n");
    }
    return 0;
}

int _print(File fp, const char *fmt, va_list ap) {
    int r = 0;
    for (int i = 0; fmt[i]; i++) {
        if (fmt[i] != '%') {
            r += fprintf(fp, "%c", fmt[i]);
            continue;
        }
        if (fmt[++i] == '\0') break;
        Token *token = NULL;
        switch (fmt[i]) {
            case 's': r += fprintf(fp, "%s", va_arg(ap, char*)); break;
            case 'd': r += fprintf(fp, "%d", va_arg(ap, int)); break;
            case 'c': r += fprintf(fp, "%c", va_arg(ap, int)); break;
            case 'f': r += fprintf(fp, "%f", va_arg(ap, double)); break;
            case 'z': r += fprintf(fp, "%zu", va_arg(ap, size_t)); i++; break;
            case 'i': r += fprintf(fp, "%*s", va_arg(ap, int), ""); break;
            case '%': r += fprintf(fp, "%%"); break;
            case 't': r += fprintf(fp, "%s", to_string(va_arg(ap, Type))); break;
            case 'k': r += _print_token(fp, va_arg(ap, Token*)); break;
            case 'n': r += _print_node(fp, va_arg(ap, Node *)); break;
            case 'N': r += _print_type(fp, va_arg(ap, Node*)); break;
            default : break;
        }
    }
    return r;
}
// clang-format on

char *format(char *fmt, ...) {
    char *buf = NULL;
    size_t size = 0;
    File out = open_memstream(&buf, &size);
    if (!out) {
        eprint("open_memstream failed\n");
        exit(1);
    }

    va_list ap;
    va_start(ap, fmt);
    _print(out, fmt, ap);
    va_end(ap);

    fclose(out);
    char *res = ura_dup(buf);
    free(buf);
    return res;
}

int _eprint(char *file, const char *func, int line, char *fmt, ...) {
    ura.errors_count++;
    va_list args;
    va_start(args, fmt);
    int r = fprintf(stderr, RED("%s:%d %s") " ", file, line, func);
    r += _print(stderr, fmt, args);
    va_end(args);
    return r;
}

int print(char *fmt, ...) {
    va_list args;
    va_start(args, fmt);
    int r = _print(stdout, fmt, args);
    va_end(args);
    return r;
}

void error(int line, int s, int e, char *msg) {
    char *name = ura.scope->token->name;
    char *buff = ura.scope->token->file.buff;

    int s0 = s;
    int e0 = e;
    while (s0 > 0 && buff[s0 - 1] != '\n')
        s0--;
    while (buff[e0] && buff[e0] != '\n')
        e0++;
    print("%d -> %d\n", s0, e0);

    int col = s - s0 + 1;
    fprintf(stderr, RED("error:") " %s:%d:%d %s\n", name, line, col, msg);

    int width = snprintf(NULL, 0, "%d", line);
    fprintf(stderr, "%*s |\n", width, "");                    // 1st line
    fprintf(stderr, "%d | %.*s\n", line, e0 - s0, buff + s0); // error line
    fprintf(stderr, "%*s | %*s", width, "", s - s0, "");      // ^ left space
    for (int i = s; i < e || i == s; i++)
        fputc('^', stderr);
    fprintf(stderr, "\n");
}